version: "3.9"

services:
  api:
    build: ./backend
    container_name: greenkode_api
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mysql
    networks:
      - greenkode_net

  angular:
    build: ./frontend
    container_name: greenkode_frontend
    restart: always
    ports:
      - "4200:4200"   # ‚Üê Correct for ng serve
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ng serve --host 0.0.0.0 --poll 2000
    depends_on:
      - api
    networks:
      - greenkode_net

  mysql:
    image: mysql:8.0
    container_name: greenkode_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: eazy
      MYSQL_DATABASE: greenkode
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - greenkode_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: greenkode_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: eazy
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - greenkode_net

networks:
  greenkode_net:
    driver: bridge

volumes:
  mysql_data:
